services:
  portal-frontend:
    container_name: portal-frontend
    image: genaidews/chat:latest
    ports:
      - "8090:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data:/data
    environment:
      TZ: "Asia/Seoul"